// <auto-generated />
using System;
using diricoAPIs.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


namespace diricoAPIs.Migrations
{
    [DbContext(typeof(diricoDBContext))]
    [Migration("20200620121350_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("diricoAPIs.Models.AssetModel", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssetFileName")
                        .IsRequired();

                    b.Property<string>("AssetFilePath")
                        .IsRequired();

                    b.Property<int>("AssetType");

                    b.Property<DateTime>("Datetime");

                    b.Property<string>("MetaData");

                    b.Property<Guid>("Parent");

                    b.Property<Guid>("UserRef");

                    b.HasKey("AssetId");

                    b.HasIndex("UserRef");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("diricoAPIs.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserId = new Guid("cc3cfd90-a036-425e-90dc-745a48e38aba"), FirstName = "FirstName", LastName = "LastName", UserName = "Admin" }
                    );
                });

            modelBuilder.Entity("diricoAPIs.Models.AssetModel", b =>
                {
                    b.HasOne("diricoAPIs.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserRef")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
