// <auto-generated />
using System;
using diricoAPIs.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace diricoAPIs.Migrations
{
    [DbContext(typeof(diricoDBContext))]
    partial class diricoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("diricoAPIs.Models.AssetModel", b =>
                {
                    b.Property<Guid>("AssetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssetFileName")
                        .IsRequired();

                    b.Property<string>("AssetFilePath")
                        .IsRequired();

                    b.Property<int>("AssetType");

                    b.Property<DateTime>("Datetime");

                    b.Property<string>("MetaData");

                    b.Property<Guid?>("Parent");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("diricoAPIs.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserId = new Guid("6b60c4b8-dac2-48e3-b329-628a9c4a01be"), FirstName = "FirstName", LastName = "LastName", UserName = "Admin" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
